// **** what is javascript **** :-

// → javascript is dynamic computer programing language. 
// → JS is the most-popular programming language to build interactive websites.
// → It is easy to learn and syntax is very simple.
// → It is a lightweight, and OOP language. 
// → JavaScript is a scripting language for web pages.
// → JavaScript file is saved with ".js" extension.

// javascript was first known as livescript, but netscape changed its name to javascript, possibly becauase of the excitement being  generated by java. 
// javascript made its first appearance in netscape 2.0 in 1995 with the name livescript. 
// the general-purpose core of the language has been embedded in netscape, internet explorer, and other web browsers.

// **** js Advantages ****:-

// → Fast execution
// → open and cross-platform
// → JavaScript supports all modern browser
// → Used to make user-friendly websites
// → Very popular and large-community support
// → It separates HTML and code
// → It makes HTML and JavaScript easier to read and maintain
// → Cached JavaScript files can speed up page loads
// → complementry to and integrated with html.
// → Reduces the server load because it executes on the client side


// *** Features of javascript *** :-

// → Light Weight and interpreted language
// → Highly case-sensitive
// → Object Oriented Programming
// → Allow developers to create form validations on  input fields.
// → High-level and dynamically typed programming language.


//**** why javascript **** :-

// → html to defined the content web pages 
// → css to specify the layout of web pages 
// → javascript to program the behavior of web pages 


// *** javascript value ***  :- 

// → fixed values are called literals.
// → variable values are called variables


// → HTML is the markup language that we use to structure and give meaning to our web content, 
//      for example defining paragraphs, headings, and data tables, or embedding images and videos in the page.

// → CSS is a language of style rules that we use to apply styling to our HTML content,
//     for example setting background colors and fonts, and laying out our content in multiple columns.

// → JavaScript is a scripting language that enables you to create dynamically updating content,  control multimedia, animate images, and pretty much everything else. 
// (Okay, not everything, but it is amazing what you can achieve with a few lines of JavaScript code.)
  

// ** Data types **

// Primitive Data Types:
// Number       =   5, 6.5, 7 etc
// String       =   “Hello everyone” etc
// Boolean      =   true or false
// Null         =  represents null i.e. no value at all
// Undefined    =  A variable that has not been assigned a value is undefined.
// Symbol       =  used as an identifier for object properties.
 
// Non-Primitive Data Types:
// Object       =  instance through which we can access members
// Array        =  group of similar values
// RegExp       =  represents regular expression
 


 
// ** using consol in javascript ** :-
// The console.log() is a function in javascript that is used to print any kind of variable defined before in it or just print any message that needs to be displayed to the users.

// // {
//     console.log("hello world");
//     console.log("hello javascript");
//     console.log("80");
//     var a=50;
// }

// ** javascript language case-sensitive variable in javascript ** :-
// {
//     names="css"; 
//     console.log(names);
//     names="kishan";
//     console.log(names);

//     var Names="website";
//     var names="javascript";
//     console.log(names);

//     var thisis="50 ";
//     var thatis="25";
//     console.log(thisis + thatis);

//     var box1="colthes";
//     var box1="toys";
//     console.log(box1);
// }

//  ** new html element add in though javascript ** :-
{
    // var newelement=document.createElement("h1");
    // newelement.textContent="bhalala kishan";
    // document.body.appendChild(newelement); 

    // var newelement=document.createElement("marquee");
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement); 
}

// ** using the DOM API ** 
// {
//     var a = 40;
//     var b = 30;
//     var b = "hi, i am javascript don't afraid of me."
//     document.getElementById("demo1").innerHTML = a;
//     document.getElementById("demo2").innerHTML = b;
// }

// let variable (blockscope variables)
// {
//     let boxx1 = "toys1";
//     let boxx2 = "clothes1";
//     boxx1 = "toys2";
//     boxx2 = "clothes2";
//     boxx2="foo";
//     document.getElementById("demo3").innerHTML=boxx2;
// }

// const variable (blockscope variables)
// {
//     const toys="bus";
//     const toys1="car";
//     document.getElementById("demo4").innerHTML=toys;
//     document.getElementById("demo4").innerHTML=toys1;
// }


// ** js comment **

//single-line comments (//)
/* multi-line comments */


// ** Template literals ** 

// var _nameone = "5";
// var name20 = '5';

// console.log(_nameone+name20);

//  alert(`${_nameone} + ${name20}`); 


// ** Rules for Naming JavaScript Variables ** 

// {
//     //valid
//     let a = 'hello';
//     let _a = 'hello';
//     let $a = 'hello';
// }
{
    //invalid
    // Let 1a = 'hello'; // this gives an error
}

// ** JavaScript is case-sensitive. So y and Y are different variables ** 

// {
//     let y = "hi";
//     let Y = 5;

//     console.log(y);
//     console.log(Y);
// }

// ** Keywords cannot be used as variable names. ** 

{
    //invalid
    // let new = 5; // Error! new is a keyword.
}




